import SideNavigation from './SideNavigation'
import TopNavigation from './TopNavigation'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'JoeBhoi',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-zinc-700 text-zinc-300">
        <div className='flex flex-col border-2 border-green-500 h-[calc(100dvh)]'> 
          <TopNavigation/>
          <div className='flex border-2 border-blue-500 flex-1'>
            <SideNavigation/>
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
